<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32046" started-at="2019-09-12T14:50:29Z" finished-at="2019-09-12T14:51:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32046" started-at="2019-09-12T14:50:29Z" finished-at="2019-09-12T14:51:01Z">
      <class name="webServicesTest.ExtentReportsTest">
        <test-method status="PASS" signature="Setup()[pri:0, instance:webServicesTest.ExtentReportsTest@67784306]" name="Setup" is-config="true" duration-ms="26403" started-at="2019-09-12T20:20:29Z" finished-at="2019-09-12T20:20:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:webServicesTest.ExtentReportsTest@67784306]" name="test2" duration-ms="609" started-at="2019-09-12T20:20:56Z" finished-at="2019-09-12T20:20:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at webServicesTest.ExtentReportsTest.test2(ExtentReportsTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="getresult(org.testng.ITestResult)[pri:0, instance:webServicesTest.ExtentReportsTest@67784306]" name="getresult" is-config="true" duration-ms="5" started-at="2019-09-12T20:20:57Z" finished-at="2019-09-12T20:20:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test2 status=FAILURE method=ExtentReportsTest.test2()[pri:0, instance:webServicesTest.ExtentReportsTest@67784306] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getresult -->
        <test-method status="PASS" signature="test1()[pri:1, instance:webServicesTest.ExtentReportsTest@67784306]" name="test1" duration-ms="17" started-at="2019-09-12T20:20:57Z" finished-at="2019-09-12T20:20:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="getresult(org.testng.ITestResult)[pri:0, instance:webServicesTest.ExtentReportsTest@67784306]" name="getresult" is-config="true" duration-ms="1" started-at="2019-09-12T20:20:57Z" finished-at="2019-09-12T20:20:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test1 status=SUCCESS method=ExtentReportsTest.test1()[pri:1, instance:webServicesTest.ExtentReportsTest@67784306] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getresult -->
        <test-method status="PASS" signature="testclose()[pri:0, instance:webServicesTest.ExtentReportsTest@67784306]" name="testclose" is-config="true" duration-ms="4051" started-at="2019-09-12T20:20:57Z" finished-at="2019-09-12T20:21:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testclose -->
      </class> <!-- webServicesTest.ExtentReportsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
